### ISSUE TITLE
Add source for srec s19 files

### ISSUE THREAD

**Issue by IntergalacticMicrosystems** [TheSonicZone/PROG05#1]
I don't see the source for the srec s19 files - like memread and memwrite.

Would it be possible to upload those?

Great project - thanks!

**Comment by TheSonicZone** [comment]
Thank you.
Yes the source files are in a virtual machine (Windows XP) because the toolchains for HC05 are very old applications and won't run on any modern Windows or CPU. I will need to retrieve them out of the virtual machine and commit them

**Comment by TheSonicZone** [comment]
The files were located in the Windows XP virtual machine- this took time because I had to recover the systems due to issues/problems with VMWare Player acting up on latest updated Windows 10 22H2.

Please check commit a4768cc for these files
